config/routes.rb
Demigod::Application.routes.draw do
  resources :statistics

  resources :histories

  resources :user_challenges

  resources :challenges

  root :to => "home#index"
  get "/admin", to: "users#admin", as: "admin"
  get "/admin_challenges", to: "users#admin_challenges", as: "admin_challenges"
  get "/take_challenge/:id", to: "challenges#take_challenge", as: "take_challenge"
  get "/post_to_wall/:challenge_id", to: "users#post_to_wall", as: "wall_post"
  get "/create_history/:currProgress", to: "users#create_history", as: "create_history"
  get "/can_next_checkin_occur", to: "users#can_next_checkin_occur", as: "can_next_checkin_occur"
  get "/get_checkin_count", to: "users#get_checkin_count", as: "get_checkin_count"
  get "/get_progress", to: "users#get_progress", as: "get_progress"
  get "/has_user_finished_this_week", to: "users#has_user_finished_this_week", as: "has_user_finished_this_week"
  get "/users/:id/progress", to: "users#progress", as: "progress"
  get "/is_the_first_day_of_the_week", to: "users#is_the_first_day_of_the_week", as: "is_the_first_day_of_the_week"
  get "/get_start_of_next_week", to: "users#get_start_of_next_week", as: "get_start_of_next_week"
  get "/my_challenges", to: "users#my_challenges", as: "my_challenges"
  get "/completed_challenges", to: "users#completed_challenges", as: "completed_challenges"
  get "/list/:challenge_type", to: "challenges#challenge_type_index", as: "challenge_type"
  get "/nutritional", to: "home#nutritional", as: "nutritional"
  get "/physical", to: "home#physical", as: "physical"
  get "/intellectual", to: "home#intellectual", as: "intellectual"
  get "/category/nutritional", to: "challenges#nutritional_des", as: "nutritional_des"
  get "/category/physical", to: "challenges#physical_des", as: "physical_des"
  get "/category/intellectual", to: "challenges#intellectual_des", as: "intellectual_des"
  get "/abandon_challenge/:user_id", to: "user_challenges#abandon_challenge", as: "abandon_challenge"
  get "/faq", to: "home#faq", as: "faq"
  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :via => :post
  devise_for :users, :controllers => {omniauth_callbacks: "users/omniauth_callbacks", :registrations => "registrations"}
  resources :users
end

app/models/user_challenge.rb
class UserChallenge < ActiveRecord::Base
  belongs_to :challenge
  belongs_to :user
  has_many :histories
end

app/controllers/user_challenges_controller.rb
class UserChallengesController < ApplicationController
  before_action :set_user_challenge, only: [:show, :edit, :update, :destroy]

  # GET /user_challenges
  # GET /user_challenges.json
  def index
    @user_challenges = UserChallenge.all
  end

  # GET /user_challenges/1
  # GET /user_challenges/1.json
  def show
  end

  # GET /user_challenges/new
  def new
    @user_challenge = UserChallenge.new
  end

  # GET /user_challenges/1/edit
  def edit
  end

  # POST /user_challenges
  # POST /user_challenges.json
  def create
    @user_challenge = UserChallenge.new(user_challenge_params)

    respond_to do |format|
      if @user_challenge.save
        format.html { redirect_to @user_challenge, notice: 'User challenge was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user_challenge }
      else
        format.html { render action: 'new' }
        format.json { render json: @user_challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_challenges/1
  # PATCH/PUT /user_challenges/1.json
  def update
    respond_to do |format|
      if @user_challenge.update(user_challenge_params)
        format.html { redirect_to @user_challenge, notice: 'User challenge was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user_challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_challenges/1
  # DELETE /user_challenges/1.json
  def destroy
    @user_challenge.destroy
    respond_to do |format|
      format.html { redirect_to user_challenges_url }
      format.json { head :no_content }
    end
  end
  
    
  def abandon_challenge
    user_id = params[:user_id]
    uc = UserChallenge.where(user_id: user_id, finished: false).last
    if uc.present?
      hist = History.where(user_challenge_id: uc.id, user_id: user_id)
      weeks = Week.where(user_challenge_id: uc.id, user_id: user_id)
      hist.destroy_all
      uc.destroy 
      weeks.destroy_all     
    end
    redirect_to user_path(current_user)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_challenge
      @user_challenge = UserChallenge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_challenge_params
      params.require(:user_challenge).permit(:challenge_id, :end_date, :user_id, :progress, :type)
    end
end

app/helpers/user_challenges_helper.rb
module UserChallengesHelper
end

app/views/user_challenges/_form.html.haml
= form_for @user_challenge do |f|
  - if @user_challenge.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user_challenge.errors.count, "error")} prohibited this user_challenge from being saved:"
      %ul
        - @user_challenge.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :challenge_id
    = f.number_field :challenge_id
  .field
    = f.label :end_date
    = f.datetime_select :end_date
  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :progress
    = f.number_field :progress
  .field
    = f.label :type
    = f.text_field :type
  .actions
    = f.submit 'Save'

app/views/user_challenges/edit.html.haml
%h1 Editing user_challenge

= render 'form'

= link_to 'Show', @user_challenge
\|
= link_to 'Back', user_challenges_path

app/views/user_challenges/index.html.haml
%h1 Listing user_challenges

%table
  %tr
    %th Challenge
    %th End date
    %th User
    %th Progress
    %th Type
    %th
    %th
    %th

  - @user_challenges.each do |user_challenge|
    %tr
      %td= user_challenge.challenge_id
      %td= user_challenge.end_date
      %td= user_challenge.user_id
      %td= user_challenge.progress
      %td= user_challenge.type
      %td= link_to 'Show', user_challenge
      %td= link_to 'Edit', edit_user_challenge_path(user_challenge)
      %td= link_to 'Destroy', user_challenge, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User challenge', new_user_challenge_path

app/views/user_challenges/new.html.haml
%h1 New user_challenge

= render 'form'

= link_to 'Back', user_challenges_path

app/views/user_challenges/show.html.haml
%p#notice= notice

%p
  %b Challenge:
  = @user_challenge.challenge_id
%p
  %b End date:
  = @user_challenge.end_date
%p
  %b User:
  = @user_challenge.user_id
%p
  %b Progress:
  = @user_challenge.progress
%p
  %b Type:
  = @user_challenge.type

= link_to 'Edit', edit_user_challenge_path(@user_challenge)
\|
= link_to 'Back', user_challenges_path