config/routes.rb
Demigod::Application.routes.draw do
  resources :statistics

  resources :histories

  resources :user_challenges

  resources :challenges

  root :to => "home#index"
  get "/admin", to: "users#admin", as: "admin"
  get "/admin_challenges", to: "users#admin_challenges", as: "admin_challenges"
  get "/take_challenge/:id", to: "challenges#take_challenge", as: "take_challenge"
  get "/post_to_wall/:challenge_id", to: "users#post_to_wall", as: "wall_post"
  get "/create_history/:currProgress", to: "users#create_history", as: "create_history"
  get "/can_next_checkin_occur", to: "users#can_next_checkin_occur", as: "can_next_checkin_occur"
  get "/get_checkin_count", to: "users#get_checkin_count", as: "get_checkin_count"
  get "/get_progress", to: "users#get_progress", as: "get_progress"
  get "/has_user_finished_this_week", to: "users#has_user_finished_this_week", as: "has_user_finished_this_week"
  get "/users/:id/progress", to: "users#progress", as: "progress"
  get "/is_the_first_day_of_the_week", to: "users#is_the_first_day_of_the_week", as: "is_the_first_day_of_the_week"
  get "/get_start_of_next_week", to: "users#get_start_of_next_week", as: "get_start_of_next_week"
  get "/my_challenges", to: "users#my_challenges", as: "my_challenges"
  get "/completed_challenges", to: "users#completed_challenges", as: "completed_challenges"
  get "/list/:challenge_type", to: "challenges#challenge_type_index", as: "challenge_type"
  get "/nutritional", to: "home#nutritional", as: "nutritional"
  get "/physical", to: "home#physical", as: "physical"
  get "/intellectual", to: "home#intellectual", as: "intellectual"
  get "/category/nutritional", to: "challenges#nutritional_des", as: "nutritional_des"
  get "/category/physical", to: "challenges#physical_des", as: "physical_des"
  get "/category/intellectual", to: "challenges#intellectual_des", as: "intellectual_des"
  get "/abandon_challenge/:user_id", to: "user_challenges#abandon_challenge", as: "abandon_challenge"
  get "/faq", to: "home#faq", as: "faq"
  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :via => :post
  devise_for :users, :controllers => {omniauth_callbacks: "users/omniauth_callbacks", :registrations => "registrations"}
  resources :users
end

app/models/statistic.rb
class Statistic < ActiveRecord::Base
  has_many :user_statistics
  has_many :challenge_statistics
  has_many :challenges, :through => :challenge_statistics
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  before_action :set_statistic, only: [:show, :edit, :update, :destroy]

  # GET /statistics
  # GET /statistics.json
  def index
    @statistics = Statistic.all
  end

  # GET /statistics/1
  # GET /statistics/1.json
  def show
  end

  # GET /statistics/new
  def new
    @statistic = Statistic.new
  end

  # GET /statistics/1/edit
  def edit
  end

  # POST /statistics
  # POST /statistics.json
  def create
    @statistic = Statistic.new(statistic_params)

    respond_to do |format|
      if @statistic.save
        format.html { redirect_to @statistic, notice: 'Statistic was successfully created.' }
        format.json { render action: 'show', status: :created, location: @statistic }
      else
        format.html { render action: 'new' }
        format.json { render json: @statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statistics/1
  # PATCH/PUT /statistics/1.json
  def update
    respond_to do |format|
      if @statistic.update(statistic_params)
        format.html { redirect_to @statistic, notice: 'Statistic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statistics/1
  # DELETE /statistics/1.json
  def destroy
    @statistic.destroy
    respond_to do |format|
      format.html { redirect_to statistics_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_statistic
      @statistic = Statistic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def statistic_params
      params.require(:statistic).permit(:user_id, :level, :name, :points_until_level_up)
    end
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/views/statistics/_form.html.haml
= form_for @statistic do |f|
  - if @statistic.errors.any?
    #error_explanation
      %h2= "#{pluralize(@statistic.errors.count, "error")} prohibited this statistic from being saved:"
      %ul
        - @statistic.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :level
    = f.number_field :level
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :points_until_level_up
    = f.number_field :points_until_level_up
  .actions
    = f.submit 'Save'

app/views/statistics/edit.html.haml
%h1 Editing statistic

= render 'form'

= link_to 'Show', @statistic
\|
= link_to 'Back', statistics_path

app/views/statistics/index.html.haml
%h1 Listing statistics

%table
  %tr
    %th User
    %th Level
    %th Name
    %th Points until level up
    %th
    %th
    %th

  - @statistics.each do |statistic|
    %tr
      %td= statistic.user_id
      %td= statistic.level
      %td= statistic.name
      %td= statistic.points_until_level_up
      %td= link_to 'Show', statistic
      %td= link_to 'Edit', edit_statistic_path(statistic)
      %td= link_to 'Destroy', statistic, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Statistic', new_statistic_path

app/views/statistics/new.html.haml
%h1 New statistic

= render 'form'

= link_to 'Back', statistics_path

app/views/statistics/show.html.haml
%p#notice= notice

%p
  %b User:
  = @statistic.user_id
%p
  %b Level:
  = @statistic.level
%p
  %b Name:
  = @statistic.name
%p
  %b Points until level up:
  = @statistic.points_until_level_up

= link_to 'Edit', edit_statistic_path(@statistic)
\|
= link_to 'Back', statistics_path