config/routes.rb
Demigod::Application.routes.draw do
  resources :statistics

  resources :histories

  resources :user_challenges

  resources :challenges

  root :to => "home#index"
  get "/admin", to: "users#admin", as: "admin"
  get "/admin_challenges", to: "users#admin_challenges", as: "admin_challenges"
  get "/take_challenge/:id", to: "challenges#take_challenge", as: "take_challenge"
  get "/post_to_wall/:challenge_id", to: "users#post_to_wall", as: "wall_post"
  get "/create_history/:currProgress", to: "users#create_history", as: "create_history"
  get "/can_next_checkin_occur", to: "users#can_next_checkin_occur", as: "can_next_checkin_occur"
  get "/get_checkin_count", to: "users#get_checkin_count", as: "get_checkin_count"
  get "/get_progress", to: "users#get_progress", as: "get_progress"
  get "/has_user_finished_this_week", to: "users#has_user_finished_this_week", as: "has_user_finished_this_week"
  get "/users/:id/progress", to: "users#progress", as: "progress"
  get "/is_the_first_day_of_the_week", to: "users#is_the_first_day_of_the_week", as: "is_the_first_day_of_the_week"
  get "/get_start_of_next_week", to: "users#get_start_of_next_week", as: "get_start_of_next_week"
  get "/my_challenges", to: "users#my_challenges", as: "my_challenges"
  get "/completed_challenges", to: "users#completed_challenges", as: "completed_challenges"
  get "/list/:challenge_type", to: "challenges#challenge_type_index", as: "challenge_type"
  get "/nutritional", to: "home#nutritional", as: "nutritional"
  get "/physical", to: "home#physical", as: "physical"
  get "/intellectual", to: "home#intellectual", as: "intellectual"
  get "/category/nutritional", to: "challenges#nutritional_des", as: "nutritional_des"
  get "/category/physical", to: "challenges#physical_des", as: "physical_des"
  get "/category/intellectual", to: "challenges#intellectual_des", as: "intellectual_des"
  get "/abandon_challenge/:user_id", to: "user_challenges#abandon_challenge", as: "abandon_challenge"
  get "/faq", to: "home#faq", as: "faq"
  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :via => :post
  devise_for :users, :controllers => {omniauth_callbacks: "users/omniauth_callbacks", :registrations => "registrations"}
  resources :users
end

app/models/history.rb
class History < ActiveRecord::Base
  belongs_to :user
  belongs_to :user_challenge
  belongs_to :week
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :set_history, only: [:show, :edit, :update, :destroy]

  # GET /histories
  # GET /histories.json
  def index
    @histories = History.all
  end

  # GET /histories/1
  # GET /histories/1.json
  def show
  end

  # GET /histories/new
  def new
    @history = History.new
  end

  # GET /histories/1/edit
  def edit
  end

  # POST /histories
  # POST /histories.json
  def create
    @history = History.new(history_params)

    respond_to do |format|
      if @history.save
        format.html { redirect_to @history, notice: 'History was successfully created.' }
        format.json { render action: 'show', status: :created, location: @history }
      else
        format.html { render action: 'new' }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /histories/1
  # PATCH/PUT /histories/1.json
  def update
    respond_to do |format|
      if @history.update(history_params)
        format.html { redirect_to @history, notice: 'History was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /histories/1
  # DELETE /histories/1.json
  def destroy
    @history.destroy
    respond_to do |format|
      format.html { redirect_to histories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_history
      @history = History.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def history_params
      params.require(:history).permit(:user_id, :user_challenge_id, :progress)
    end
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/views/histories/_form.html.haml
= form_for @history do |f|
  - if @history.errors.any?
    #error_explanation
      %h2= "#{pluralize(@history.errors.count, "error")} prohibited this history from being saved:"
      %ul
        - @history.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :user_challenge_id
    = f.number_field :user_challenge_id
  .field
    = f.label :progress
    = f.number_field :progress
  .actions
    = f.submit 'Save'

app/views/histories/edit.html.haml
%h1 Editing history

= render 'form'

= link_to 'Show', @history
\|
= link_to 'Back', histories_path

app/views/histories/index.html.haml
%h1 Listing histories

%table
  %tr
    %th User
    %th User challenge
    %th Progress
    %th
    %th
    %th

  - @histories.each do |history|
    %tr
      %td= history.user_id
      %td= history.user_challenge_id
      %td= history.progress
      %td= link_to 'Show', history
      %td= link_to 'Edit', edit_history_path(history)
      %td= link_to 'Destroy', history, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New History', new_history_path

app/views/histories/new.html.haml
%h1 New history

= render 'form'

= link_to 'Back', histories_path

app/views/histories/show.html.haml
%p#notice= notice

%p
  %b User:
  = @history.user_id
%p
  %b User challenge:
  = @history.user_challenge_id
%p
  %b Progress:
  = @history.progress

= link_to 'Edit', edit_history_path(@history)
\|
= link_to 'Back', histories_path