config/routes.rb
Demigod::Application.routes.draw do
  resources :statistics

  resources :histories

  resources :user_challenges

  resources :challenges

  root :to => "home#index"
  get "/admin", to: "users#admin", as: "admin"
  get "/admin_challenges", to: "users#admin_challenges", as: "admin_challenges"
  get "/take_challenge/:id", to: "challenges#take_challenge", as: "take_challenge"
  get "/post_to_wall/:challenge_id", to: "users#post_to_wall", as: "wall_post"
  get "/create_history/:currProgress", to: "users#create_history", as: "create_history"
  get "/can_next_checkin_occur", to: "users#can_next_checkin_occur", as: "can_next_checkin_occur"
  get "/get_checkin_count", to: "users#get_checkin_count", as: "get_checkin_count"
  get "/get_progress", to: "users#get_progress", as: "get_progress"
  get "/has_user_finished_this_week", to: "users#has_user_finished_this_week", as: "has_user_finished_this_week"
  get "/users/:id/progress", to: "users#progress", as: "progress"
  get "/is_the_first_day_of_the_week", to: "users#is_the_first_day_of_the_week", as: "is_the_first_day_of_the_week"
  get "/get_start_of_next_week", to: "users#get_start_of_next_week", as: "get_start_of_next_week"
  get "/my_challenges", to: "users#my_challenges", as: "my_challenges"
  get "/completed_challenges", to: "users#completed_challenges", as: "completed_challenges"
  get "/list/:challenge_type", to: "challenges#challenge_type_index", as: "challenge_type"
  get "/nutritional", to: "home#nutritional", as: "nutritional"
  get "/physical", to: "home#physical", as: "physical"
  get "/intellectual", to: "home#intellectual", as: "intellectual"
  get "/category/nutritional", to: "challenges#nutritional_des", as: "nutritional_des"
  get "/category/physical", to: "challenges#physical_des", as: "physical_des"
  get "/category/intellectual", to: "challenges#intellectual_des", as: "intellectual_des"
  get "/abandon_challenge/:user_id", to: "user_challenges#abandon_challenge", as: "abandon_challenge"
  get "/faq", to: "home#faq", as: "faq"
  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :via => :post
  devise_for :users, :controllers => {omniauth_callbacks: "users/omniauth_callbacks", :registrations => "registrations"}
  resources :users
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "danger"}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .brand
      = link_to '', root_path, class: 'brand' 
    .navbar-header#top-spacing
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    .collapse.navbar-collapse
      %ul.nav.navbar-nav#top-spacing
        = render 'layouts/navigation_links'
      -if user_signed_in?
        %ul.nav.navbar-nav.pull-right#top-spacing  
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
              #{current_user.name.downcase}
              %b.caret
            %ul.dropdown-menu
              %li
                = link_to 'edit account', edit_user_registration_path
              %li.divider
              %li
                = link_to 'my challenges', my_challenges_path
              %li.divider
              %li
                = link_to 'completed challenges', completed_challenges_path
              %li.divider
              %li  
                = link_to 'logout', destroy_user_session_path, :method=>'delete'  

app/views/layouts/_navigation_links.html.haml
/ add navigation links to this file
- if user_signed_in? 
  %li= link_to 'home', user_path(current_user)
  %li= link_to 'challenges', challenges_path
  %li= link_to 'progress', progress_path(current_user)
  %li= link_to 'faq', faq_path
  %li= link_to 'contact', contact_path
  - if current_user.has_role? :admin
    %li= link_to "administrator controls", admin_path 
- else
  %li= link_to 'home', root_path
  %li= link_to 'login', new_user_session_path
  %li= link_to 'sign up', new_user_registration_path
  %li= link_to 'sign in with facebook', user_omniauth_authorize_path(:facebook)
  %li= link_to 'contact', contact_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Demigod'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Demigod'}"}
    = favicon_link_tag 'favicon.ico'
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    .container.wrapper
      %header
        = render 'layouts/navigation'
      %main{:role => "main"}
        = render 'layouts/messages'
        = yield
      %div.push
         
    -# Footer section
    %footer#jm-footer
      .container#footer-color
        .row
          .span6
            #jm-copyrights
              .copyrights.count_1
                .row#row-footer
                  .copyrights-in.span0
                    .copyrights-bg
                      .jm-module
                        .jm-module-in
                          .jm-module-content.clearfix
                            .custom
                              %p
                                copyright #{Time.now.year} 
                              %p#copyright-font  
                                all rights reserved
          .span6.pull-right
            #jm-poweredby-styleswitcher.pull-right
              #jm-poweredby{style: "margin-top: 10px"}
                %a{href: "http://www.demigod.me", onfocus: "blur()", target: "_blank", title: "Demigod"}
                  demigod.me
    

app/views/layouts/modal.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Demigod'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Demigod'}"}
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = render 'layouts/messages'
    = yield